### ISSUE TITLE
Should return direct references to loaders, as well as overall config

### ISSUE THREAD

**Issue by keeganstreet** [DeloitteDigitalAPAC/webpack-config#19]
I find myself needing to tweak the options for loaders on projects, for example to pass project-specific options into Sass. The current implementation does not make it easy to do this. Instead of just returning `module.exports = config;`, we could return direct references to loaders to enable projects to tweak their options, i.e.:

```
module.exports = {
  config,
  loaders: {
    cssLoader,
    postcssLoader,
    sassLoader,
  },
};
```

This allows projects to do this:

```
const { config, loaders } = require('@deloitte-digital-au/webpack-config');

loaders.sassLoader.options = ...;
```

**Comment by jennasalau** [comment]
Hey Keegan,

I'm not so sure this is a pattern we should be promoting. There is a couple of reasons I think why:

1. It breaks the single responsibility rule. The import just looks messy now and its not immediately clear whats going on or what you are supposed to do with loaders.
1. We are relying way to much on mutating objects for my liking. Mutating the loaders here you are also in effect mutating config too.  This is not an example I want to be setting for our engineers to follow in projects, I much prefer everything to be functional.
1. You can still modify loaders currently without exposing them, this is just trying to shortcut the process.

I would much prefer we recommend using something like **Smart Merging** https://github.com/survivejs/webpack-merge#smart-merging

In fact I kinda think we should recommend webpack-merge for making project specific changes. That way you are never mutating the original.

**Comment by keeganstreet** [comment]
Thanks Jenna, a very insightful review! Smart merging looks very cool. I have done a quick test and it allows me to add an option to the sassLoader without having to re-write any of the existing options, so that is great. I'll try putting this in and update my PR.

**Test:**
```
const merge = require('webpack-merge');
const path = require('path');

const config1 = {
	module: {
		rules: [
			{
				test: /\.scss$/,
				use: {
					loader: 'sass-loader',
					options: {
						data: '$IS_DEBUG: true;',
					},
				},
			},
		],
	},
};

const config2 = {
	module: {
		rules: [
			{
				test: /\.scss$/,
				use: {
					loader: 'sass-loader',
					options: {
						includePaths: [ path.resolve(__dirname, './my-unusual-include-path') ],
					},
				},
			},
		],
	},
};

var output = merge.smart(config1, config2);

console.log(JSON.stringify(output, null, 2));
```

**Output:**
Correctly contains both options (data and includePaths).
```
{
  "module": {
    "rules": [
      {
        "test": {},
        "use": [
          {
            "loader": "sass-loader",
            "options": {
              "data": "$IS_DEBUG: true;",
              "includePaths": [
                "/Users/kestreet/Downloads/webpack-merge-test/my-unusual-include-path"
              ]
            }
          }
        ]
      }
    ]
  }
}
```

**Comment by jennasalau** [comment]
Awesome.

Maybe we should have a think about including this tool as a dependency and exposing it all encapsulated instead?

eg our api could change to

    import config from '@deloitte-digital-au/webpack-config';

    module.exports = config.merge({
         entry: '/hey/im/overriding/entry/with/zero/config'
    });

Food for thought. Not even I'm 💯 sure about this

**Comment by keeganstreet** [comment]
Its an interesting idea. For now, I will use `webpack-merge` in my project as a test run, and see how that goes, while we think about whether we want to bring it in to this package.

**Comment by keeganstreet** [comment]
Closing following discussion. Don't want to promote mutating imported configs. Webpack-merge is added in https://github.com/DeloitteDigitalAPAC/webpack-config/pull/11/
