### ISSUE TITLE
Missing file loader

### ISSUE THREAD

**Issue by jennasalau** [DeloitteDigitalAPAC/webpack-config#26]
It seems out of the box we are not falling back to a [file loader](https://github.com/webpack-contrib/file-loader).

We should probably include this in the base webpack config for the usual suspects: 

`/\.(svg|png|jpg|gif|eot|ttf|woff|woff2)$/`

**Comment by keeganstreet** [comment]
I tend to put static files in the `public` dir, but agree this would  be useful to allow these files to be used in the `src` dir.
