### ISSUE TITLE
Consider adding a history api fallback out of the box

### ISSUE THREAD

**Issue by jennasalau** [DeloitteDigitalAPAC/webpack-config#30]
**webpack-server** doesn't ship with a history api fallback out of the box 😢.

Nearly everyone of our projects is going to need this so I think we should contemplate adding it in right out of the box. We will need to follow the example here: https://github.com/webpack-contrib/webpack-serve/blob/master/docs/addons/history-fallback.config.js

**Comment by jennasalau** [comment]
Yeah thats all good. 

This issue is to make our dev server return the index.html for deep links.

They used to support it in `webpack-dev-server` https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback

But now with `webpack-serve` you need to install it as a plugin https://github.com/bripkens/connect-history-api-fallback

**Comment by keeganstreet** [comment]
I feel that this would be making some app architecture assumptions that are
too specific for this package. Not all projects built with this package are
single page apps with serverside rendering (or even single page apps where
the server serves index.html at other paths). Would it be ok to install the
plugin at the project level?

**Comment by jennasalau** [comment]
I wasn't planning on blindly turning it on.

Just bringing back a feature like `historyApiFallback: true` and keeping a single configuration package since we do do many SPA's.

Perhaps, ill just add a guide on how to install it and set it up.

**Comment by keeganstreet** [comment]
Hey Jenna, sorry I must have misunderstood. I think it would be fine to add
it if it's not enabled by default.
