### ISSUE TITLE
What do we think about automated dependency managment?

### ISSUE THREAD

**Issue by jennasalau** [DeloitteDigitalAPAC/webpack-config#5]
What do we think about using a service like https://dependabot.com/ (free) or https://greenkeeper.io/ to help keep our dependencies up to date?

https://dependabot.com/#how-it-works

It's an annoying task and this project has many dependencies. The bots will automatically create PR's for us so we choose what goes in or not and it runs our tests.

Thoughts?

**Comment by keeganstreet** [comment]
Love the idea. I haven't looked into which service is most suitable yet though. Another one to consider is [Renovate](https://github.com/apps/renovate). Was chatting to a platforms guy from SEEK recently, this is what they are using.

**Comment by keeganstreet** [comment]
Also would be great to get automated PRs opened in our projects when we release new versions of `webpack-config`, so Bitbucket integration would be a plus.

**Comment by jennasalau** [comment]
Renovate looks super cool... Shall we try that? 

The ones I found require admin access on your repo which I don't understand why when it just creates PR's.

**Comment by dkeeghan** [comment]
Renovate looks great. This will be very useful. Nice find.

**Comment by keeganstreet** [comment]
It works! https://github.com/DeloitteDigitalAPAC/webpack-config/pull/11
